// ============================
// ENUMS — Jewellery ERP Domain
// ============================

export enum MetalType {
  GOLD = 'GOLD',
  SILVER = 'SILVER',
  PLATINUM = 'PLATINUM',
  PALLADIUM = 'PALLADIUM',
  OTHER = 'OTHER',
}

export enum Purity {
  K24 = '24K',
  K22 = '22K',
  K20 = '20K',
  K18 = '18K',
  K14 = '14K',
  K10 = '10K',
  SILVER_999 = 'SILVER_999',
  SILVER_925 = 'SILVER_925',
  SILVER_900 = 'SILVER_900',
  SILVER_800 = 'SILVER_800',
}

export enum JewelleryStatus {
  IN_STOCK = 'IN_STOCK',
  RESERVED = 'RESERVED',
  SOLD = 'SOLD',
  RETURNED = 'RETURNED',
  EXCHANGED = 'EXCHANGED',
  IN_REPAIR = 'IN_REPAIR',
  IN_MANUFACTURING = 'IN_MANUFACTURING',
  TRANSFERRED = 'TRANSFERRED',
  MELTED = 'MELTED',
  SCRAPPED = 'SCRAPPED',
}

export enum MakingChargeType {
  PERCENTAGE = 'PERCENTAGE',
  PER_GRAM = 'PER_GRAM',
  FIXED_AMOUNT = 'FIXED_AMOUNT',
}

export enum ChargeType {
  MAKING = 'MAKING',
  HALLMARK = 'HALLMARK',
  STONE = 'STONE',
  LABOUR = 'LABOUR',
  CERTIFICATION = 'CERTIFICATION',
  OTHER = 'OTHER',
}

export enum BillType {
  GST = 'GST',
  NON_GST = 'NON_GST',
  MANUAL = 'MANUAL',
  ESTIMATE = 'ESTIMATE',
  PROFORMA = 'PROFORMA',
}

export enum BillStatus {
  DRAFT = 'DRAFT',
  CONFIRMED = 'CONFIRMED',
  FINALIZED = 'FINALIZED',
  CANCELLED = 'CANCELLED',
  RETURNED = 'RETURNED',
  PARTIALLY_RETURNED = 'PARTIALLY_RETURNED',
  ADJUSTED = 'ADJUSTED',
}

export enum PaymentMode {
  CASH = 'CASH',
  UPI = 'UPI',
  DEBIT_CARD = 'DEBIT_CARD',
  CREDIT_CARD = 'CREDIT_CARD',
  BANK_TRANSFER = 'BANK_TRANSFER',
  CHEQUE = 'CHEQUE',
  OTHER = 'OTHER',
}

export enum TransactionType {
  PURCHASE = 'PURCHASE',
  SALE = 'SALE',
  SALE_RETURN = 'SALE_RETURN',
  MANUFACTURING_ISSUE = 'MANUFACTURING_ISSUE',
  MANUFACTURING_RETURN = 'MANUFACTURING_RETURN',
  EXCHANGE_OUT = 'EXCHANGE_OUT',
  EXCHANGE_IN = 'EXCHANGE_IN',
  URD_RECEIVE = 'URD_RECEIVE',
  TRANSFER = 'TRANSFER',
  ADJUSTMENT = 'ADJUSTMENT',
  MELTING = 'MELTING',
  SCRAPPED = 'SCRAPPED',
  OPENING_BALANCE = 'OPENING_BALANCE',
}

export enum JobStatus {
  ASSIGNED = 'ASSIGNED',
  ACCEPTED = 'ACCEPTED',
  IN_PROGRESS = 'IN_PROGRESS',
  QUALITY_CHECK = 'QUALITY_CHECK',
  READY = 'READY',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}

export enum RepairStatus {
  RECEIVED = 'RECEIVED',
  ASSIGNED = 'ASSIGNED',
  IN_REPAIR = 'IN_REPAIR',
  READY = 'READY',
  DELIVERED = 'DELIVERED',
}

export enum NotificationType {
  JOB_READY = 'JOB_READY',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  ORDER_READY = 'ORDER_READY',
  BILL_GENERATED = 'BILL_GENERATED',
  OUTSTANDING_REMINDER = 'OUTSTANDING_REMINDER',
  JOB_DELAYED = 'JOB_DELAYED',
  REPAIR_READY = 'REPAIR_READY',
}

export enum NotificationChannel {
  IN_APP = 'IN_APP',
  WHATSAPP = 'WHATSAPP',
  SMS = 'SMS',
  EMAIL = 'EMAIL',
}

export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  OWNER = 'OWNER',
  BRANCH_MANAGER = 'BRANCH_MANAGER',
  ACCOUNTANT = 'ACCOUNTANT',
  SALESMAN = 'SALESMAN',
  CASHIER = 'CASHIER',
  INVENTORY_MANAGER = 'INVENTORY_MANAGER',
  BARCODE_OPERATOR = 'BARCODE_OPERATOR',
  GOLDSMITH = 'GOLDSMITH',
  KARIGAR = 'KARIGAR',
  JOB_WORKER = 'JOB_WORKER',
}

export enum Permission {
  // Billing
  BILLING_VIEW = 'BILLING_VIEW',
  BILLING_CREATE = 'BILLING_CREATE',
  BILLING_EDIT_DRAFT = 'BILLING_EDIT_DRAFT',
  BILLING_FINALIZE = 'BILLING_FINALIZE',
  BILLING_CANCEL = 'BILLING_CANCEL',
  BILLING_RETURN = 'BILLING_RETURN',

  // Inventory
  INVENTORY_VIEW = 'INVENTORY_VIEW',
  INVENTORY_ADJUST = 'INVENTORY_ADJUST',
  INVENTORY_VIEW_COST = 'INVENTORY_VIEW_COST',
  INVENTORY_TRANSFER = 'INVENTORY_TRANSFER',

  // Customers
  CUSTOMERS_VIEW = 'CUSTOMERS_VIEW',
  CUSTOMERS_CREATE = 'CUSTOMERS_CREATE',
  CUSTOMERS_EDIT = 'CUSTOMERS_EDIT',

  // Employees
  EMPLOYEES_VIEW = 'EMPLOYEES_VIEW',
  EMPLOYEES_MANAGE = 'EMPLOYEES_MANAGE',

  // Job Work
  JOB_WORK_VIEW = 'JOB_WORK_VIEW',
  JOB_WORK_CREATE = 'JOB_WORK_CREATE',
  JOB_WORK_ASSIGN = 'JOB_WORK_ASSIGN',

  // Reports
  REPORTS_VIEW = 'REPORTS_VIEW',
  REPORTS_GST = 'REPORTS_GST',
  REPORTS_FINANCIAL = 'REPORTS_FINANCIAL',
  REPORTS_EXPORT = 'REPORTS_EXPORT',

  // Financial
  PROFIT_VIEW = 'PROFIT_VIEW',
  SALARY_VIEW = 'SALARY_VIEW',
  PURCHASE_COST_VIEW = 'PURCHASE_COST_VIEW',

  // Settings
  SETTINGS_MANAGE = 'SETTINGS_MANAGE',
  USERS_MANAGE = 'USERS_MANAGE',
  ROLES_MANAGE = 'ROLES_MANAGE',
  BRANCHES_MANAGE = 'BRANCHES_MANAGE',

  // Audit
  AUDIT_VIEW = 'AUDIT_VIEW',
}